### ISSUE TITLE
webp 403 응답

### ISSUE THREAD

**Issue by pompitzz** [TASK-FORCE/mannalga-api#399]
@SightStudio 
몇몇 webp 이미지에 403응답이 오네요. 확인 가능 할까요??

https://super-invention-static.s3.ap-northeast-2.amazonaws.com/temp/img/20201118103423-c702c611-b3b8-45bc-980f-6c4b0ca74edb-test.webp
https://super-invention-static.s3.ap-northeast-2.amazonaws.com/temp/img/20201118103423-c702c611-b3b8-45bc-980f-6c4b0ca74edb-test.png

**Comment by SightStudio** [comment]
temp/img 하위 디렉토리에 있는 파일은 따로 변환을 하지 않도록 해서 발생한 이슈같네요  

원래는 404가 맞지만 조회하는 유저에게는 버킷에 관한 권한이 없기때문에 403을 내려준다고 하네요.
현재처럼 저런 경우에는 fallback 처리가 되서 원본 이미지를 가져오도록 하면 될것같아요 

https://stackoverflow.com/questions/37708059/amazon-s3-returns-403-error-instead-of-404-despite-getobject-allowance

**Comment by pompitzz** [comment]
@SightStudio 
현재 모임 이미지를 변경해도 temp/img에 들어가는데
temp/img 디렉토리로 들어가는 조건이 무엇인가요?

**Comment by SightStudio** [comment]
아 정준님이 작업했던부분이네요. 커뮤니케이션이 안됫던것같군요 ㅜㅜ

해당 API도 다음과 같이 변경해야할것같네요 
http://mannal.ga:8082/docs/index.html#_%EB%AA%A8%EC%9E%84_%EC%83%9D%EC%84%B1

AS-IS
![image](https://user-images.githubusercontent.com/50672087/115118553-b7caa800-9fde-11eb-87fd-52a6752dc292.png)

TO-BE
![image](https://user-images.githubusercontent.com/50672087/115118543-aaadb900-9fde-11eb-8831-2eb18cd5146f.png)

**Comment by SightStudio** [comment]
temp/img 에 들어가는 조건은 파일 임시저장 했을때만입니다.

추후에 크론잡으로 삭제될 파일들입니다 ㅎㅎ

**Comment by yyy9942** [comment]
크론잡이라함은... 쿠버네티스 도입을 암시하는건가요? ㅋㅋ

**Comment by SightStudio** [comment]
```js
img : {
    "absolutePath": ~,
    "filePath" : ~ 
    "fileName": ~ 
}
```

로 진행해주시면 될것같아요

**Comment by pompitzz** [comment]
수정되면 알려주세요

**Comment by SightStudio** [comment]
위 논의한 부분은 새로 이슈만들어서 진행하겠습니다. 해당이슈 닫도록하겠습니다.
